[theme]
primaryColor = "#6667AB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true

[cache]
type = "filesystem"
